---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

env:
  global:
    - AWS_DEFAULT_REGION="us-east-1"
    # AWS_ACCESS_KEY_ID
    - secure: "o3ToIvNo72KWyQn44mqmDGQa5LWz/wpPdJZMyVpugg+H+SzPQ9Riyl9\
      3Gip4VlN5CHLRZvsXi3JsGN/nunbN+xZxuGXwEWoET8wkmWV3V4uve2An+4eHG6r\
      v0xGLrTo+yWKMkcsnXHZdNCCGtC81UwCxI3n6tUzk9OtU0TBi8KW/2ZBnFox0kwr\
      2C/S//R5egVl2i25GIOS8IHdTBPIZEfvYf7TczJVtaLjzsusCM4kyn4WC/Wc0SUI\
      gdGxmj8I18MCHPFXazm6ltF6IUe1LwerERXvfeRSbi5bhD8JlmGRjbnzCLHq0WdW\
      9j8Hqeq7zGSvfUWPjDZp7ObgC/jShflaSfHrvRJDdpeSn/zn1Ar/aSXOe/0uoXRn\
      XzBOGxwrbOZ7p6UrDJqYu4QecRMKOWwf5D5+27ehKUp5tQ8jUeIp7C4g46W8rXVY\
      ribP2e8J1Y1dy4t1GRrFo2K7sLU8rlCz+1N/hlswihVlCTD53jMg/nhdkhg41U8x\
      MoZ+L139+cahIM9L3sjKMYaGc5SVuSBoMLQQCklHmvjL85o+ut1r2vdye7IY0Esw\
      TDS6D8XOSg/ctK57RDUhEOsd65NMn+BO9aOaBY/PElBcweBf33IigffRP3Knh3Xv\
      vIJXz7PTT2VX6dPkrHLDuVCMQyIWbIb+gKjDi4Riy28B3M0Pzxho="
    # AWS_SECRET_ACCESS_KEY
    - secure: "K33aZe/R4oIE5VVY5+x076HE7+/TdPswvCW7HS3KKSRq9kmMvP/m9zX\
      o882xsvGh1UpxOCpuFWbyEQOukHm0aumtzNjkPbrnNB889jqOxsakql7pvetLvAc\
      T3JlfADx8aXlMjtz7mnsLjveKSI7HPc7eQipbNHlLC7cpAe++nQw0sKjCD3LL5Zb\
      MB4BCAgI8cTk2sbTg8eUA/qns/Cse1gTRp2q86XdfHV0++m6RA3kzbwluA/TQi83\
      0aQiasAbiUVCrZE8QseAMPArkKiy5ZvTYxqcNFsfZTvb50gPtklNvgM9P3uze6PG\
      jRXW41YRLwFlWrAdp/r9IJa2FE1RO/vFDAcjMo++V5FvE4rgCsHocnQaN8Zz0Kos\
      8Lj5LIj+bTl+pOR7tLdE6Z5/jBlEWljr6O7oR5dj7o+gAOlrEIM3zIG4JPC1Imor\
      EdnYRH76kXp9/aQic46yJqJMwieFH3HluIULP2Fe/I0fxgxcC4DSuQq8lE32E1kR\
      xPSmc+iPj3NOH7MuosGhxGOKMzAR+Zk1YVubaBMO9uyRKG6POfzz92sHNhrMdUB0\
      g5ju4P65ghTHk+49JlduGOajJM8PbO7UG56SPy1sLnroizDa3uhtlyHb+VjUV1WH\
      OjDRu5Qgm2Tm7ou3AhZFI9B3DWIYQlHZN6AXhZVSCDmOW/nQI+as="

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

# Install terraform and terraform-doc
before_install:
  - >
    wget
    https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
    -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - go get github.com/segmentio/terraform-docs

install:
  - pip install --upgrade -r requirements-test.txt

script:
  - pre-commit run --all-files
  - molecule test
