---
# tasks file for ncats_webd

- name: Install cisagov/cyhy-core
  ansible.builtin.include_role:
    name: cyhy_core
  vars:
    cyhy_core_maxmind_license_key: "{{ ncats_webd_maxmind_license_key }}"

- name: Install system versions of the Python packages that ncats-webd needs
  ansible.builtin.package:
    name:
      # Note that the gunicorn package is the command and python-gunicorn
      # is the Python 2 library.
      - gunicorn
      - python-cffi
      - python-dateutil
      - python-docopt
      - python-flask
      - python-gevent
      - python-greenlet
      - python-gunicorn
      - python-netaddr
      - python-schedule

- name: Install the ncats-webd package
  ansible.builtin.pip:
    executable: /usr/bin/pip2
    name:
      - https://api.github.com/repos/cisagov/ncats-webd/tarball/testing/mcdonnnj
