---
# tasks file for ncats_webd

#
# Grab the ncats-webd code
#
- name: Create the /var/local/ncats-webd directory
  file:
    path: /var/local/ncats-webd
    state: directory

- name: Download and untar the ncats-webd tarball
  unarchive:
    src: "https://api.github.com/repos/jsf9k/ncats-webd/tarball/pin_flask-caching_version?\
    access_token={{ github_oauth_token }}"
    dest: /var/local/ncats-webd
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

#
# Install ncats-webd
#
- name: Install ncats-webd
  pip:
    name: file:///var/local/ncats-webd
