---
- name: cyhy_core
  src: https://github.com/cisagov/ansible-role-cyhy-core
- name: pip
  src: https://github.com/cisagov/ansible-role-pip
- name: python
  src: https://github.com/cisagov/ansible-role-python
- name: upgrade
  src: https://github.com/cisagov/ansible-role-upgrade
